apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solar-system-dev
resources:
  - namespace.yaml
  - ../../base
images:
  - name: aunghtetlwin/solar-system-app
    newName: aunghtetlwin/solar-system-app
    newTag: b756e827ca4bd8fddf067cabbbcdaf229a0fab19
patches:
  - target:
      kind: Ingress
      name: solar-system-app
    patch: |-
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1load-balancer-name
        value: solar-system-dev-alb
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1listen-ports
        value: '[{"HTTP":80}]'
      - op: remove
        path: /metadata/annotations/alb.ingress.kubernetes.io~1ssl-redirect
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1tags
        value: Project=solar-system,Environment=dev,ManagedBy=argocd
      - op: replace
        path: /spec/rules/0/host
        value: dev.solar-system.aunghtetlwin.com
