services:
  app:
    image: aunghtetlwin/solar-system-app:v1
    container_name: solar-system-app
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/solar-system
      MONGO_USERNAME: ""
      MONGO_PASSWORD: ""
    ports:
      - "3000:3000"

  mongo:
    image: mongo:7
    container_name: solar-system-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo-data:
