apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: solar-system
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: solar-system
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
