apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-system-platform
  namespace: argocd
spec:
  project: solar-system
  source:
    repoURL: https://github.com/aunghtetlwin-gh/Solar-system-cicd-eks.git
    targetRevision: main
    path: kubernetes/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
