apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: solar-system
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: solar-system
type: Opaque
stringData:
  MONGO_USERNAME: solar-admin
  MONGO_PASSWORD: change-me-before-production
